# Utilise l'image officielle Python 3.11
FROM python:3.11

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier des dépendances
COPY requirements.txt .

# Installer les dépendances Python
RUN pip install -r requirements.txt

# Copier le code de l'application dans le conteneur
COPY . .

# Exposer le port sur lequel l'API écoute
EXPOSE 5000

# Commande par défaut pour démarrer l'API
CMD ["python", "app.py"]